
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      NODE_ENV: development
    depends_on:
      - backend
